"""add player dispatch

Revision ID: 87da87cc3bf9
Revises: 66f148fd0bf7
Create Date: 2023-08-07 20:23:46.781666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87da87cc3bf9'
down_revision: Union[str, None] = '66f148fd0bf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('next_sync_time', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
    op.add_column('player', sa.Column('last_sync_time', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=False))
    op.add_column('player', sa.Column('last_match_time', sa.DateTime(), server_default='1970-01-01 00:00:00', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'last_match_time')
    op.drop_column('player', 'last_sync_time')
    op.drop_column('player', 'next_sync_time')
    # ### end Alembic commands ###
