"""base

Revision ID: 92f49827b126
Revises:
Create Date: 2023-08-07 09:39:52.061365

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "92f49827b126"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
