"""add rank score

Revision ID: ec2acaccac8a
Revises: 87da87cc3bf9
Create Date: 2023-08-08 00:42:08.818996

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec2acaccac8a"
down_revision: Union[str, None] = "87da87cc3bf9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("player", sa.Column("player_rank_score", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "player_rank_score")
    # ### end Alembic commands ###
