"""add player display name

Revision ID: f08b0633e82d
Revises: ec2acaccac8a
Create Date: 2023-08-12 02:20:56.567379

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f08b0633e82d"
down_revision: Union[str, None] = "ec2acaccac8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player",
        sa.Column(
            "player_display_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player", "player_display_name")
    # ### end Alembic commands ###
